### ISSUE TITLE
Starter example doesn't work

### ISSUE THREAD

**Issue by tenstriker** [play2-maven-plugin/play2-maven-test-projects#1]
Following play-maven example doesn't work:
play2-maven-test-projects-master/play26/scala/starter-example

Instruction on page says `sbt run` and it fails as there is no `project` directory in setup which seem to be expected by sbt.

sbt run
[warn] No sbt.version set in project/build.properties, base directory: /Users/npatel/ws/play2-maven-test-projects-master/play26/scala/starter-example
[info] Set current project to starter-example (in build file:/Users/npatel/ws/play2-maven-test-projects-master/play26/scala/starter-example/)
[info] Updating {file:/Users/npatel/ws/play2-maven-test-projects-master/play26/scala/starter-example/}starter-example...
[info] Done updating.
[info] Packaging /Users/npatel/ws/play2-maven-test-projects-master/play26/scala/starter-example/target/scala-2.12/starter-example_2.12-0.1-SNAPSHOT.jar ...
[info] Done packaging.
[error] java.lang.RuntimeException: No main class detected.
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$4(Defaults.scala:1146)
[error] 	at sbt.Defaults$$$Lambda$2184/370610592.apply(Unknown Source)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$3(Defaults.scala:1146)
[error] 	at sbt.Defaults$$$Lambda$1649/468797188.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$767/1481853275.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1689/81705968.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.Execute$$Lambda$1700/262908478.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.Execute$$Lambda$1692/547973118.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1699/13950734.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (compile:bgRun) No main class detected.
[error] Total time: 2 s, completed Nov 28, 2017 3:25:02 PM

**Comment by gslowikowski** [comment]
Most of the test projects are based on original Play! Framework projects available in different repositories [here](https://github.com/playframework/).
I didn't change `README.md` files, sorry. I will fix it. Of course, you have to use Maven instead od SBT, e.g. `mvn play2:run` instead of `sbt run`.
